export const DISPLAY_SIGN_UP_MODAL = "DISPLAY_SIGN_UP_MODAL";
export const DISPLAY_LOG_IN_MODAL = "DISPLAY_LOG_IN_MODAL";
export const SUBMIT_SEARCH_FIELD = "SUBMIT_SEARCH_FIELD";
export const SUBMIT_EMAIL = "SUBMIT_EMAIL";
export const SUBMIT_CRYPTED_PASSWORD = "SUBMIT_CRYPTED_PASSWORD";
export const LOG_IN = "LOG_IN";
export const SUBMIT_NAME = "SUBMIT_NAME";
export const IS_LOGGED_IN = "IS_LOGGED_IN";
export const LOAD_USER = "LOAD_USER";
export const RESET_USER = "RESET_USER";
export const IS_MOBILE = "IS_MOBILE";
export const DISPLAY_MOBILE_MENU = "DISPLAY_MOBILE_MENU";
export const UN_DISPLAY_MOBILE_MENU = "UN_DISPLAY_MOBILE_MENU";

